CREATE TABLE IF NOT EXISTS LOGIN_USER (
  ID INT AUTO_INCREMENT,
  EMAIL VARCHAR(60),
  USERNAME VARCHAR(60),
  PASSWORD VARCHAR(60),
  PRIMARY KEY(ID),
  UNIQUE KEY IDX_LU_1(EMAIL)
)
AUTO_INCREMENT = 10001;
