CREATE TABLE LOGIN_USER (
  ID INT AUTO_INCREMENT,
  EMAIL VARCHAR(60),
  USERNAME VARCHAR(60),
  PASSWORD VARCHAR(60),
  PRIMARY KEY(ID),
  UNIQUE KEY IDX_LU_1(EMAIL)
)
AUTO_INCREMENT = 10001;

CREATE TABLE CHANNEL (
  ID INT AUTO_INCREMENT,
  NAME VARCHAR(60),
  VISIBILITY CHAR(1),
  PRIMARY KEY(ID)
)
AUTO_INCREMENT = 10001;

CREATE TABLE TALK (
  ID INT AUTO_INCREMENT,
  CHANNELID INT,
  USERID INT,
  CREATE_TIME TIMESTAMP,
  CONTENTS TEXT,
  PRIMARY KEY(ID),
  INDEX IDX_TK_1(CHANNELID)
)
AUTO_INCREMENT = 10001;

CREATE TABLE USER_CHANNELS (
  USERID INT,
  CHANNELID INT,
  OWNER VARCHAR(5),
  PRIMARY KEY(USERID, CHANNELID)
);
